<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Form\ConfirmForm $form
 * @var string $resourceLabel
 * @var string $language
 * @var array $translations
 * @var bool $wrapSidebar
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');

$form->setAttribute('action', $url('admin/translation/id', ['action' => 'delete', 'language' => $language]));
$form->setButtonLabel('Confirm delete'); // @translate
?>

<?php if ($wrapSidebar): ?>
<div id="delete" class="sidebar">
    <?= $hyperlink('', '#', ['class' => 'sidebar-close o-icon-close', 'title' => $translate('Close')]) ?>
<?php endif; ?>
    <div id="sidebar-confirm">
        <?php $resourceLabel = $translate($resourceLabel); ?>
        <h3><?= sprintf($translate('Delete translations for "%s"'), $language) ?></h3>
        <p><?= sprintf($translate('Are you sure you would like to delete this %s?'), $resourceLabel) ?></p>
        <?= $this->form($form) ?>
    </div>
<?php if ($wrapSidebar): ?>
</div>
<?php endif; ?>
