<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 *
 * @uses \Internationalisation\View\Helper\LanguageSwitcher
 */

$plugins = $this->getHelperPluginManager();
$languageSwitcher = $plugins->get('languageSwitcher');
?>

<div class="block resource-block block-language-switcher">
    <?= $languageSwitcher() ?>
</div>
