<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var array $locales
 * @var array $locale_labels
 * @var bool $locale_as_code
 */

?>

<?php if ($locales): ?>
    <?php $currentLocale = $this->siteSetting('locale') ?: 'en_US'; ?>
    <ul class="language-switcher <?= $locale_as_code ? 'locale-code' : 'locale-flag' ?>">
        <?php if ($locale_as_code): ?>

        <?php foreach ($locales as $locale): ?>
            <?php $country = $this->localeToCountry($locale['locale']); ?>
            <li>
                <?php if ($currentLocale == $locale['locale']): ?>
                    <span class="active" title="<?= $locale['locale_label'] ?>"><?= strtolower(substr($locale['locale'], 0, 2)) ?></span>
                <?php else: ?>
                    <a href="<?= $locale['url'] ?>" title="<?= $locale['locale_label'] ?>"><?= strtolower(substr($locale['locale'], 0, 2)) ?></a>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>

        <?php else: ?>

        <?php foreach ($locales as $locale): ?>
            <?php $country = $this->localeToCountry($locale['locale']); ?>
            <li>
                <?php if ($currentLocale == $locale['locale']): ?>
                    <span class="active flag-icon flag-icon-<?= strtolower($country) ?>" title="<?= $locale['locale_label'] ?>"></span>
                <?php else: ?>
                    <a href="<?= $locale['url'] ?>" title="<?= $locale['locale_label'] ?>"><span class="flag-icon flag-icon-<?= strtolower($country) ?>"></span></a>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>

        <?php endif; ?>
    </ul>
<?php endif; ?>
